# Generated by Django 2.2.9 on 2022-04-08 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220408_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='title_group',
            new_name='title',
        ),
    ]
